Repository revolist/revogrid, pull requests merged in 2025-04, with the labels that each got.

#729 breaking change: advance grouping template
  src/components/data/revogr-data-style.scss
  src/components/data/revogr-data.tsx
  src/plugins/groupingRow/grouping.row.renderer.tsx
  src/plugins/groupingRow/grouping.row.types.ts
  src/serve/controller.js
  src/types/interfaces.ts
Labels: feature, breaking-change

#733 feat: core version upgrade
  package-lock.json
  package.json
  src/plugins/wcag/index.ts
Labels: feature

#741 fix: #740 - recalculate viewport size on header and footer change
  package-lock.json
  package.json
  src/components.d.ts
  src/components/revoGrid/revo-grid.tsx
  src/components/revoGrid/viewport.resize.service.ts
  src/components/scroll/revogr-viewport-scroll.tsx
  src/utils/resize-observer.polifill.ts
Labels: bug
